### ISSUE TITLE
Installed blueprint but nothing happens

### ISSUE THREAD

**Issue by phateks** [arnie580/hass-blueprints#1]
Hello, recently i bought some sonoff trvzb's and looking for implementing an external sensor calibration for them and found your project, but after installing blueprint when i hit run, nothing happens. Is there anything else in installing this so it can work?
Are you using ZHA or Zigbee2MQTT ?

Thank you!!

**Comment by arnie580** [comment]
Hi, apologies for the delay in replying, unsure if it's still relevant I wasn't really expecting anyone other than myself to use this so never thought to check the issues but you're more than welcome! 

It's set up for zigbee2mqtt using the default topics for devices.

Nothing else should be required.

**Comment by arnie580** [comment]
Ok so it appears with it being summer here it had stopped working due to a change with Z2M and I hadn't noticed.

I have now updated this blueprint to work with the new Z2M implementation.
