### ISSUE TITLE
[FR]: add support for ZHA

### ISSUE THREAD

**Issue by LazyT** [arnie580/hass-blueprints#2]
Hi,

could you please add support for ZHA too?

As far as I understand it just needs another action:

`action:
- service: number.set_value
  target:
    entity_id: !input offset_entity
  data:
    value: '{{ (sensor_temp - (trv_temp - trv_offset)) | round(1) }}'
- delay: 5`

I tried the above and it seems to work fine here.

Maybe add an additional setup field for choosing between Z2M and ZHA?

Thank you very much!

**Comment by arnie580** [comment]
Change made. There is no need for separate actions for ZHA and Z2M as it appears both create the offset calibration entity.
